# This file was generated by GoReleaser. DO NOT EDIT.
cask "bdinfo" do
  name "bdinfo"
  desc "Go rewrite of BDInfo."
  homepage "https://github.com/s0up4200/go-bdinfo"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bdinfo"

  on_macos do
    on_intel do
      url "https://github.com/s0up4200/go-bdinfo/releases/download/v#{version}/bdinfo_#{version}_darwin_amd64.tar.gz"
      sha256 "2a79d1d568daf4164196dc02d6d25a4c8b0d4ee8c83327580a4b906537b05618"
    end
    on_arm do
      url "https://github.com/s0up4200/go-bdinfo/releases/download/v#{version}/bdinfo_#{version}_darwin_arm64.tar.gz"
      sha256 "d07fbf9dee15fc90220d29d3d2569176fc90d9cfe4156abf157173ee995a32dd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/s0up4200/go-bdinfo/releases/download/v#{version}/bdinfo_#{version}_linux_amd64.tar.gz"
      sha256 "a1527480234b6c666778455bfb8bf989f449e9cf29d6261be10f1ec245f5d317"
    end
    on_arm do
      url "https://github.com/s0up4200/go-bdinfo/releases/download/v#{version}/bdinfo_#{version}_linux_arm64.tar.gz"
      sha256 "2ad45ab11624504ca6503dc6b0bfa2bbd0d88e2c13d39b48f986654f87255f3f"
    end
  end

  # No zap stanza required
end
