# This file was generated by GoReleaser. DO NOT EDIT.
cask "bdinfo" do
  version "0.4.1"

  on_macos do
    on_arm do
      sha256 "4e0a75816a183d2b2fff56e7b10357c915cdc54ba7a57c5aec2bc607415a641a"
      url "https://github.com/autobrr/go-bdinfo/releases/download/v#{version}/bdinfo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5fa713e8b84b57db083ab10f293a0204ba7dbade6f2ed75d932fbcecfc027947"
      url "https://github.com/autobrr/go-bdinfo/releases/download/v#{version}/bdinfo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bf38bad183900657208649b7fc7926caa37a290bb3efba709c719e93c75f39d2"
      url "https://github.com/autobrr/go-bdinfo/releases/download/v#{version}/bdinfo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bc7980120f33fc13813732589e06bb2918c992170b03356b0bf5d1717d24d36b"
      url "https://github.com/autobrr/go-bdinfo/releases/download/v#{version}/bdinfo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "bdinfo"
  desc "Go rewrite of BDInfo."
  homepage "https://github.com/autobrr/go-bdinfo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bdinfo"

  # No zap stanza required
end
