# This file was generated by GoReleaser. DO NOT EDIT.
cask "bdinfo" do
  name "bdinfo"
  desc "Go rewrite of BDInfo."
  homepage "https://github.com/s0up4200/go-bdinfo"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bdinfo"

  on_macos do
    on_intel do
      url "https://github.com/s0up4200/go-bdinfo/releases/download/v#{version}/bdinfo_#{version}_darwin_amd64.tar.gz"
      sha256 "617c804fcd605908dbdee2a738952cd7952776f5374f6ee29df2a67f21641d6f"
    end
    on_arm do
      url "https://github.com/s0up4200/go-bdinfo/releases/download/v#{version}/bdinfo_#{version}_darwin_arm64.tar.gz"
      sha256 "32be5f0ff1cb0017e0c964ca881ab053b8f9bfe1fdacec30ec6401f4939a4ac2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/s0up4200/go-bdinfo/releases/download/v#{version}/bdinfo_#{version}_linux_amd64.tar.gz"
      sha256 "82150732c8a07ab29ebabb0d659419b26bf8396c84438748d484f701bc7f5454"
    end
    on_arm do
      url "https://github.com/s0up4200/go-bdinfo/releases/download/v#{version}/bdinfo_#{version}_linux_arm64.tar.gz"
      sha256 "05304679a9163b1119bdb64f77a747428acef99c4eb34aa291e040b5e47b5576"
    end
  end

  # No zap stanza required
end
